# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-IRC
version:      4.95
version_from: lib/POE/Component/IRC.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.3202
    POE::Filter::IRCD:             1.7
    POSIX:                         0
    Socket:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
