author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Component::IRC
name: POE-Component-IRC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  POE: 0.3202
  POE::Filter::IRCD: 1.7
  POSIX: 0
  Socket: 0
  warnings: 0
version: 5.13
