# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-IRC
version:      4.79
version_from: lib/POE/Component/IRC.pm
installdirs:  site
requires:
    Carp:                          0
    Date::Format:                  0
    POE:                           0.3202
    POE::Component::Client::DNS:   0.98
    POE::Component::Client::Ident: 0.7
    POE::Filter::IRCD:             1.4
    Socket:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
