--- 
abstract: a fully event-driven IRC client module.
author: Chris Williams <chris@bingosnet.co.uk>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-IRC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  POE: 0.3202
  POE::Filter::IRCD: 1.7
  POSIX: 0
  Socket: 0
  warnings: 0
tests: t/*.t t/*/*.t
version: 5.34
