---
abstract: 'A fully event-driven IRC client module'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Encode: 0
  Encode::Guess: 0
  POE: 0.3202
  POE::Component::Pluggable: 1.12
  POE::Driver::SysRW: 0
  POE::Filter::IRCD: 1.7
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 5.94
